name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: g++ -o stirling_2.so -shared ./src/main.cpp -fPIC
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: stirling_2.so
